#!/usr/bin/env bash

if [[ -f "$HOME/.config/pecan.css" ]] && [[ ! -f "$PWD/pecan/pecan.css" ]]; then
	ln -s "$HOME/.config/pecan.css" "$PWD/pecan/pecan.css"
	osascript -e "tell application id \"tracesOf.Uebersicht\" to refresh"
fi
if [[ -f "$HOME/.cache/wal/colors.css" ]] && [[ ! -f "$PWD/pecan/colors.css" ]]; then
	ln -s "$HOME/.cache/wal/colors.css" "$PWD/pecan/colors.css"
	osascript -e "tell application id \"tracesOf.Uebersicht\" to refresh"
fi

exists() {
	type "$1" &>/dev/null
}

IFSTAT="${HOMEBREW_PREFIX:-/opt/homebrew}/bin/ifstat"

if exists "$IFSTAT"; then
	"$IFSTAT" -n -z -S 1 1 | awk 'FNR == 3 {print "↓ " $2 " ↑ " $3}'
else
	NETWORK=$(networksetup -getairportnetwork en0 | cut -c 24-)
	echo "↓ $NETWORK"
fi
